### PR TITLE
Rename Resident[s] to Claimant[s]

### PR DESCRIPTION
**Pull request by alex-demetriou**
#### Blocked by
- [ ] [PA-108](https://hackney.atlassian.net/browse/PA-108?atlOrigin=eyJpIjoiZDllYmQ5YmZmMWY0NDk0ZjljYmU3MmU4MDFlNTNlMDAiLCJwIjoiaiJ9) - List endpoint – search parameters & pagination
- [x] [PA-72](https://hackney.atlassian.net/browse/PA-72?atlOrigin=eyJpIjoiYTA4OGQ5NmM0ZTdiNGUwZWJlMzQ3ZDZmMWU5NTQ3ZjYiLCJwIjoiaiJ9) - Academy Resident Contact Info API - view record

#### Renamed:
 - All test method names
 - Use Case names
 - Boundary object names
 - Controller names
 - Controller endpoint
 - Domain object names
 - Factory names
 - Gateway names
 - All files to match renamed types

### CODE REVIEW

**Review by elcorbs — APPROVED** [review]

**Comment by Renny4Real** [comment]
Have merged the current changes we have for the Academy Resident Contact Info API - view record: #4

**Comment by alex-demetriou** [comment]
Now that #4 is in, are we ready to merge this? @Renny4Real 

Edit: have just spotted conflicts - resolving them now

**Comment by Renny4Real** [comment]
@alex-demetriou Oops, sorry!
I think merging in the view endpoint changes has also caused conflicts on the list endpoint PR as well. 😅 
Might be easier to get this merged in and then fix any conflicts on that branch afterwards?
@LBHBReynolds-Carr?

**Comment by alex-demetriou** [comment]
Master merged in. That wasn't too bad :sweat_smile: 
I'll merge this into origin/master now unless there are any objections @Renny4Real @LBHBReynolds-Carr

**Pull request merged**
